name: Create pull request

# プルリクが作成された時に実行する
on:
  pull_request:
    types: [
      opened,
      edited
    ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ls
        run: ls -la > output.log
      
      - name: Comment
        uses: actions/github-script@0.9.0
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: $(cat output.log)
            })
