name: Create pull request

# プルリクが作成された時に実行する
on:
  workflow_dispatch:

jobs:
  comment_on_pull_request:
    runs-on: ubuntu-latest
    steps:
      - mame: Checkout
        uses: actions/checkout@v2
        with:
          repository: notkiota/dotfiles

      - name: 
      - run: echo "Hello World!"

