name: Create pull request

# プルリクが作成された時に実行する
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.command.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Command
        id: test
        run: |
          cat README.md
      
      - name: Comment
        uses: actions/github-script@v3
        env:
          MESSAGE: |
            ### 実行結果
            ```
            ${{ steps.test.outputs.test }}
            ```
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ${{ env.MESSAGE }}
            })
