name: Create pull request

# プルリクが作成された時に実行する
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ls
        id: command
        run: |
          curl https://checkip.amazonaws.com
      
      - name: Comment
        uses: actions/github-script@v3
        env:
          MESSAGE: ${{ steps.command.outputs.result }}
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.MESSAGE + " "
            })
