name: Create pull request

# プルリクが作成された時に実行する
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ls
        id: command
        run: ls -la > output.log
      
      - name: Comment
        uses: actions/github-script@v3
        env:
          MESSAGE: |
            ### 実行結果を表示します
            #### 実行コマンド
            ```
            ${{ steps.command.outputs.command-name }} ${{ steps.command.outputs.command-arguments }}
            ```
            #### 実行結果
            ```
            ${{ steps.command.outputs }}
            ```
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.MESSAGE
            })
