name: Create pull request

# プルリクが作成された時に実行する
on:
  push:
    branches: feat/github-workflows

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Echo
        run: echo "Hello World!"

